apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secrets-store-csi
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "TALY_BE_ENV"
        objectType: "secretsmanager"
        jmesPath:
          - path: PORT
            objectAlias: port
          - path: MONGO_URL
            objectAlias: mongo_endpoint
          - path: GOOGLE_AUTH_CLIENT_ID
            objectAlias: google_client
          - path: GOOGLE_AUTH_CLIENT_SECRET
            objectAlias: google_client_secret
          - path: GOOGLE_API_KEY
            objectAlias: google_api
          - path: ADMIN_EMAIL
            objectAlias: admin_email
          - path: JWT_SECRET
            objectAlias: jwt
          - path: FE_URL
            objectAlias: fe_url
          - path: BE_URL
            objectAlias: be_url
          - path: ADMIN_SESSION_SECRET
            objectAlias: session_secret
          - path: SENDGRID_API_KEY
            objectAlias: sendgrid_api
          - path: SENDGRID_FROM
            objectAlias: sendgrid_from
          - path: AWS_REGION
            objectAlias: region
          - path: AWS_BUCKET_NAME
            objectAlias: bucket_name

  secretObjects:
    - secretName: backendsecret
      type: Opaque
      data:
        - objectName: port
          key: port
        - objectName: mongo_endpoint
          key: mongo_endpoint
        - objectName: google_client
          key: google_client
        - objectName: google_client_secret
          key: google_client_secret
        - objectName: google_api
          key: google_api
        - objectName: admin_email
          key: admin_email
        - objectName: jwt
          key: jwt
        - objectName: fe_url
          key: fe_url
        - objectName: be_url
          key: be_url
        - objectName: session_secret
          key: session_secret
        - objectName: sendgrid_api
          key: sendgrid_api
        - objectName: sendgrid_from
          key: sendgrid_from
        - objectName: region
          key: region
        - objectName: bucket_name
          key: bucket_name
