apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backend_deployment.yaml
  - autoscale.yaml
  - credentials.yaml
  - ingress.yaml

images:
  - name: XXXXXXXXXXXX.dkr.ecr.ap-southeast-1.amazonaws.com/backend
    newName: XXXXXXXXXXXX.dkr.ecr.ap-southeast-1.amazonaws.com/backend
    newTag: 4168389b53688c5f009cdebd7424e49d4354b0b9
