apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thesis
  namespace: argocd
spec:
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  source:
    path: .
    repoURL: "https://github.com/HungTuong/talyvn-manifest.git"
    targetRevision: HEAD
    kustomize:
      namespace: default
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
